import type { Dispatch, FormEvent, SetStateAction } from "react";
import type { CatalogSearchResult } from "@/lib/types";
import type {
  ItemImportPreview as ItemImportPreviewType,
  ItemImportPreviewRow,
  ItemImportResult,
  ItemImportRow,
} from "@/features/items/types";
import { ItemImportPreview } from "@/features/items/components/ItemImportPreview";

export interface ItemImportFormProps {
  csvFiles: File[];
  setCsvFiles: Dispatch<SetStateAction<File[]>>;
  csvMessage: string;
  csvResult: ItemImportResult | null;
  csvPreview: ItemImportPreviewType | null;
  submitting: boolean;
  showCsvSourceColumn: boolean;
  csvIssues: ItemImportRow[];
  onPreview: (event: FormEvent) => void;
  onConfirm: () => void;
  onResetPreview: () => void;
  onDownloadCsv: (path: string, fallbackFilename: string) => void;
  selectedCsvPreviewMatch: (row: ItemImportPreviewRow) => CatalogSearchResult | null;
  previewUnitsValue: (row: ItemImportPreviewRow) => string;
  setCsvPreviewSelections: Dispatch<SetStateAction<Record<string, CatalogSearchResult | null>>>;
  setCsvPreviewUnits: Dispatch<SetStateAction<Record<string, string>>>;
}

export function ItemImportForm({
  csvFiles,
  setCsvFiles,
  csvMessage,
  csvResult,
  csvPreview,
  submitting,
  showCsvSourceColumn,
  csvIssues,
  onPreview,
  onConfirm,
  onResetPreview,
  onDownloadCsv,
  selectedCsvPreviewMatch,
  previewUnitsValue,
  setCsvPreviewSelections,
  setCsvPreviewUnits,
}: ItemImportFormProps) {
  return (
    <section className="panel p-4">
      <h2 className="font-display text-lg font-semibold">General Items CSV Import</h2>
      <div className="mt-2 rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700">
        <p className="font-semibold text-slate-900">Use this for general item registration or alias maintenance.</p>
        <p className="mt-1">
          This path previews the CSV before import and is not limited to files generated by the missing-items workflow.
        </p>
        <p>
          Missing-item CSVs downloaded from Orders use this same import path after you fill in the required item or alias details.
        </p>
        <p className="mt-2 font-semibold text-slate-900">CSV Format</p>
        <p className="mt-1">
          Required columns: <code>item_number</code>. Optional: <code>row_type</code> (
          <code>item</code>/<code>alias</code>, defaults to <code>item</code>).
        </p>
        <p>
          Generated missing-item CSVs may use <code>resolution_type</code> (
          <code>new_item</code>/<code>alias</code>) instead of <code>row_type</code>; both are accepted.
        </p>
        <p>
          Item rows use <code>manufacturer_name</code> (or <code>manufacturer</code>),{" "}
          <code>category</code>, <code>url</code>, <code>description</code>.
        </p>
        <p>
          Alias rows require <code>supplier</code>, <code>canonical_item_number</code>, and{" "}
          <code>units_per_order</code> (&gt; 0).
        </p>
        <p>Missing manufacturer defaults to <code>UNKNOWN</code>.</p>
        <div className="mt-2 flex flex-wrap gap-2">
          <button
            className="button-subtle"
            type="button"
            onClick={() => onDownloadCsv("/items/import-template", "items_import_template.csv")}
          >
            Download Template CSV
          </button>
          <button
            className="button-subtle"
            type="button"
            onClick={() => onDownloadCsv("/items/import-reference", "items_import_reference.csv")}
          >
            Download Reference CSV
          </button>
        </div>
      </div>

      <form className="mt-3 flex flex-wrap gap-3" onSubmit={onPreview}>
        <input
          className="input max-w-xl"
          type="file"
          accept=".csv,text/csv"
          multiple
          onChange={(e) => {
            setCsvFiles(Array.from(e.target.files ?? []));
            if (csvResult !== null || csvPreview !== null) {
              onResetPreview();
            }
          }}
          required
        />
        <button className="button" disabled={submitting} type="submit">
          Preview Import
        </button>
      </form>
      <p className="mt-2 text-xs text-slate-500">
        You can select multiple CSV files; successful imports are archived under{" "}
        <code>imports/items/registered/&lt;YYYY-MM&gt;/</code>.
      </p>
      {csvMessage && <p className="mt-3 text-sm text-signal">{csvMessage}</p>}
      {csvPreview && (
        <ItemImportPreview
          csvPreview={csvPreview}
          showCsvSourceColumn={showCsvSourceColumn}
          submitting={submitting}
          onConfirm={onConfirm}
          onClearPreview={onResetPreview}
          selectedCsvPreviewMatch={selectedCsvPreviewMatch}
          previewUnitsValue={previewUnitsValue}
          setCsvPreviewSelections={setCsvPreviewSelections}
          setCsvPreviewUnits={setCsvPreviewUnits}
        />
      )}
      {csvIssues.length > 0 && (
        <div className="mt-3 overflow-x-auto rounded-xl border border-amber-200 bg-amber-50 p-3">
          <p className="mb-2 text-sm font-semibold text-amber-900">Rows with issues</p>
          <table className="min-w-[540px] text-sm">
            <thead>
              <tr className="border-b border-amber-200 text-left text-amber-800">
                {showCsvSourceColumn && <th className="px-2 py-2">File</th>}
                <th className="px-2 py-2">CSV Row</th>
                <th className="px-2 py-2">Status</th>
                <th className="px-2 py-2">Item Number</th>
                <th className="px-2 py-2">Message</th>
              </tr>
            </thead>
            <tbody>
              {csvIssues.map((row, idx) => (
                <tr key={`${row.source_name ?? "csv"}-${row.row}-${idx}`} className="border-b border-amber-100">
                  {showCsvSourceColumn && <td className="px-2 py-2">{row.source_name ?? "-"}</td>}
                  <td className="px-2 py-2">{row.row}</td>
                  <td className="px-2 py-2">{row.status}</td>
                  <td className="px-2 py-2 font-semibold">{row.item_number ?? "-"}</td>
                  <td className="px-2 py-2">{row.error ?? "-"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </section>
  );
}
